# Generated by Django 2.2.6 on 2020-04-22 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeslaAccount',
        ),
    ]
