# Generated by Django 2.2.6 on 2020-04-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0004_teslafirmwarehistory_isarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teslatoken',
            name='created_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teslatoken',
            name='expires_in',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teslatoken',
            name='refresh_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teslatoken',
            name='vehicle_id',
            field=models.TextField(null=True),
        ),
    ]
