# Generated by Django 2.2.6 on 2020-05-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0005_auto_20200429_2306'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teslafirmwarehistory',
            index=models.Index(fields=['vin', 'IsArchive'], name='matesla_tes_vin_e60d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='teslafirmwarehistory',
            index=models.Index(fields=['vin', 'Version'], name='matesla_tes_vin_d668c0_idx'),
        ),
        migrations.AddIndex(
            model_name='teslafirmwarehistory',
            index=models.Index(fields=['IsArchive', 'Version'], name='matesla_tes_IsArchi_f5819b_idx'),
        ),
        migrations.AddIndex(
            model_name='teslafirmwarehistory',
            index=models.Index(fields=['IsArchive', 'Version', 'Date'], name='matesla_tes_IsArchi_5bee0e_idx'),
        ),
        migrations.AddIndex(
            model_name='teslafirmwarehistory',
            index=models.Index(fields=['IsArchive', 'CarModel', 'Version'], name='matesla_tes_IsArchi_98993c_idx'),
        ),
        migrations.AddIndex(
            model_name='teslafirmwarehistory',
            index=models.Index(fields=['IsArchive', 'CarModel', 'Version', 'Date'], name='matesla_tes_IsArchi_4ddaff_idx'),
        ),
    ]
