# Generated by Django 2.2.6 on 2020-05-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0006_auto_20200501_1420'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teslafirmwarehistory',
            name='matesla_tes_vin_d668c0_idx',
        ),
        migrations.AddIndex(
            model_name='teslafirmwarehistory',
            index=models.Index(fields=['vin', 'vin'], name='matesla_tes_vin_6952bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='teslafirmwarehistory',
            constraint=models.UniqueConstraint(fields=('vin', 'Version', 'Date'), name='unique version at same date for car'),
        ),
        migrations.AddConstraint(
            model_name='teslatoken',
            constraint=models.UniqueConstraint(fields=('user_id', 'access_token'), name='1 token per user'),
        ),
    ]
