# Generated by Django 2.2.6 on 2020-05-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0007_auto_20200501_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeslaCarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.TextField()),
                ('Date', models.DateField()),
                ('LastSeenDate', models.DateField()),
                ('car_type', models.TextField()),
                ('charge_port_type', models.TextField()),
                ('exterior_color', models.TextField()),
                ('has_air_suspension', models.BooleanField()),
                ('has_ludicrous_mode', models.BooleanField()),
                ('motorized_charge_port', models.BooleanField()),
                ('rear_seat_heaters', models.TextField()),
                ('rhd', models.BooleanField()),
                ('roof_color', models.TextField()),
                ('wheel_type', models.TextField()),
                ('sentry_mode_available', models.BooleanField()),
                ('smart_summon_available', models.BooleanField()),
                ('eu_vehicle', models.BooleanField()),
            ],
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['vin'], name='matesla_tes_vin_539da3_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['car_type'], name='matesla_tes_car_typ_437fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['charge_port_type'], name='matesla_tes_charge__fdfcb8_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['exterior_color'], name='matesla_tes_exterio_d73144_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['has_air_suspension'], name='matesla_tes_has_air_db3494_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['has_ludicrous_mode'], name='matesla_tes_has_lud_0a8480_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['motorized_charge_port'], name='matesla_tes_motoriz_0e6bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['rear_seat_heaters'], name='matesla_tes_rear_se_1952c0_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['rhd'], name='matesla_tes_rhd_a329d2_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['roof_color'], name='matesla_tes_roof_co_188ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['wheel_type'], name='matesla_tes_wheel_t_2310de_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['sentry_mode_available'], name='matesla_tes_sentry__40d21e_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['smart_summon_available'], name='matesla_tes_smart_s_d3c323_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['eu_vehicle'], name='matesla_tes_eu_vehi_08cf33_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['charge_port_type', 'car_type'], name='matesla_tes_charge__2413f1_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['exterior_color', 'car_type'], name='matesla_tes_exterio_691c47_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['has_air_suspension', 'car_type'], name='matesla_tes_has_air_441e6e_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['has_ludicrous_mode', 'car_type'], name='matesla_tes_has_lud_314d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['motorized_charge_port', 'car_type'], name='matesla_tes_motoriz_fae86d_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['rear_seat_heaters', 'car_type'], name='matesla_tes_rear_se_d652a6_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['rhd', 'car_type'], name='matesla_tes_rhd_1cc129_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['roof_color', 'car_type'], name='matesla_tes_roof_co_9c7a10_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['wheel_type', 'car_type'], name='matesla_tes_wheel_t_84f6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['sentry_mode_available', 'car_type'], name='matesla_tes_sentry__95466a_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['smart_summon_available', 'car_type'], name='matesla_tes_smart_s_b8bf3a_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['eu_vehicle', 'car_type'], name='matesla_tes_eu_vehi_cf4cbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='teslacarinfo',
            constraint=models.UniqueConstraint(fields=('vin',), name='unique version of each car'),
        ),
    ]
