# Generated by Django 2.2.6 on 2020-05-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0008_auto_20200501_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teslacarinfo',
            name='sentry_mode_available',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='teslacarinfo',
            name='smart_summon_available',
            field=models.BooleanField(null=True),
        ),
    ]
