# Generated by Django 2.2.6 on 2020-05-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0011_auto_20200509_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
