# Generated by Django 2.2.6 on 2020-05-09 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0012_auto_20200509_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
