# Generated by Django 2.2.6 on 2020-05-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0014_auto_20200509_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='hashedVin',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teslacarinfo',
            name='hashedVin',
            field=models.TextField(null=True),
        ),
        migrations.AddIndex(
            model_name='teslacardatasnapshot',
            index=models.Index(fields=['hashedVin'], name='matesla_tes_hashedV_e74445_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['hashedVin'], name='matesla_tes_hashedV_ca469f_idx'),
        ),
    ]
