# Generated by Django 2.2.6 on 2020-05-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0015_auto_20200513_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='teslacarinfo',
            name='EPARange',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teslacarinfo',
            name='isDualMotor',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='teslacarinfo',
            name='modelYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['EPARange'], name='matesla_tes_EPARang_563a59_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['isDualMotor'], name='matesla_tes_isDualM_87ff7f_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['modelYear'], name='matesla_tes_modelYe_665ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['EPARange', 'car_type'], name='matesla_tes_EPARang_0ed0c6_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['isDualMotor', 'car_type'], name='matesla_tes_isDualM_d3abaa_idx'),
        ),
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['modelYear', 'car_type'], name='matesla_tes_modelYe_fc885e_idx'),
        ),
    ]
