# Generated by Django 2.2.6 on 2020-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0016_auto_20200517_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='battery_degradation',
            field=models.FloatField(null=True),
        ),
    ]
