# Generated by Django 3.0.6 on 2020-05-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0019_auto_20200521_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressfromlatlong',
            name='date',
            field=models.DateField(),
        ),
    ]
