# Generated by Django 3.0.6 on 2020-06-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0020_auto_20200521_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='NumberCycles',
            field=models.FloatField(null=True),
        ),
    ]
