# Generated by Django 3.0.6 on 2020-06-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0021_teslacardatasnapshot_numbercycles'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teslacarinfo',
            index=models.Index(fields=['LastSeenDate'], name='matesla_tes_LastSee_a5ef3c_idx'),
        ),
    ]
