# Generated by Django 3.0.6 on 2020-06-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0022_auto_20200626_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='randomNr',
            field=models.FloatField(null=True),
        ),
        migrations.AddIndex(
            model_name='teslacardatasnapshot',
            index=models.Index(fields=['randomNr'], name='matesla_tes_randomN_6d689b_idx'),
        ),
    ]
