# Generated by Django 3.0.6 on 2020-06-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0023_auto_20200628_0951'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teslacardatasnapshot',
            index=models.Index(fields=['hashedVin', 'randomNr'], name='matesla_tes_hashedV_c97015_idx'),
        ),
    ]
