# Generated by Django 3.0.6 on 2020-06-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0024_auto_20200628_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='teslafirmwarehistory',
            name='hashedVin',
            field=models.TextField(null=True),
        ),
        migrations.AddIndex(
            model_name='teslafirmwarehistory',
            index=models.Index(fields=['hashedVin'], name='matesla_tes_hashedV_6a7701_idx'),
        ),
    ]
