# Generated by Django 3.1.3 on 2021-02-26 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0025_auto_20200629_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllSuperchargers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SuperchargerUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_stalls', models.IntegerField()),
                ('total_stalls', models.IntegerField()),
                ('site_closed', models.BooleanField()),
                ('Date', models.DateField()),
                ('superchargerfkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matesla.allsuperchargers')),
            ],
        ),
        migrations.AddIndex(
            model_name='allsuperchargers',
            index=models.Index(fields=['name'], name='matesla_all_name_f4ba62_idx'),
        ),
        migrations.AddIndex(
            model_name='allsuperchargers',
            index=models.Index(fields=['latitude', 'longitude', 'name'], name='matesla_all_latitud_9f8fc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='allsuperchargers',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude', 'name'), name='AllSuperchargers: unique version of each charger'),
        ),
        migrations.AddIndex(
            model_name='superchargeruse',
            index=models.Index(fields=['total_stalls'], name='matesla_sup_total_s_d84368_idx'),
        ),
    ]
