# Generated by Django 3.1.8 on 2021-06-02 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0026_auto_20210226_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teslatoken',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teslatoken',
            name='expires_in',
        ),
        migrations.RemoveField(
            model_name='teslatoken',
            name='refresh_token',
        ),
    ]
