# Generated by Django 3.1.10 on 2021-08-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0027_auto_20210602_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastRequestSuperchargers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.TextField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.AddIndex(
            model_name='lastrequestsuperchargers',
            index=models.Index(fields=['vin'], name='matesla_las_vin_1a7689_idx'),
        ),
        migrations.AddConstraint(
            model_name='lastrequestsuperchargers',
            constraint=models.UniqueConstraint(fields=('vin',), name='LastRequestSuperchargers: unique version of each car'),
        ),
    ]
