# Generated by Django 3.1.10 on 2021-08-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0028_auto_20210829_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastrequestsuperchargers',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
