# Generated by Django 3.1.10 on 2021-08-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0029_auto_20210829_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superchargeruse',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
