# Generated by Django 3.1.12 on 2021-10-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0030_auto_20210829_2303'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='allsuperchargers',
            index=models.Index(fields=['type', 'latitude', 'longitude', 'name'], name='matesla_all_type_4ed830_idx'),
        ),
        migrations.AddIndex(
            model_name='allsuperchargers',
            index=models.Index(fields=['id', 'name'], name='matesla_all_id_2bbe08_idx'),
        ),
        migrations.AddIndex(
            model_name='allsuperchargers',
            index=models.Index(fields=['id'], name='matesla_all_id_cf8633_idx'),
        ),
        migrations.AddIndex(
            model_name='superchargeruse',
            index=models.Index(fields=['superchargerfkey'], name='matesla_sup_superch_acbc18_idx'),
        ),
        migrations.AddIndex(
            model_name='superchargeruse',
            index=models.Index(fields=['id', 'Date', 'available_stalls', 'total_stalls'], name='matesla_sup_id_61f288_idx'),
        ),
        migrations.AddIndex(
            model_name='superchargeruse',
            index=models.Index(fields=['Date', 'available_stalls', 'total_stalls'], name='matesla_sup_Date_56c3b0_idx'),
        ),
    ]
