# Generated by Django 5.2.16 on 2026-07-25 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0031_auto_20211005_1817'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeslaAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=128)),
                ('client_secret', models.CharField(max_length=256)),
                ('redirect_uri', models.URLField(default='http://localhost:8001/oauth/callback', help_text='Must match exactly the redirect URI registered on developer.tesla.com', max_length=512)),
                ('api_base', models.URLField(default='https://fleet-api.prd.eu.vn.cloud.tesla.com', help_text='EU: fleet-api.prd.eu… — NA: fleet-api.prd.na…', max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tesla app settings',
                'verbose_name_plural': 'Tesla app settings',
            },
        ),
        migrations.RemoveConstraint(
            model_name='teslatoken',
            name='1 token per user',
        ),
        migrations.AddField(
            model_name='teslatoken',
            name='display_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='teslatoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslatoken',
            name='refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teslatoken',
            name='vehicle_vin',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='addressfromlatlong',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='allsuperchargers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lastrequestsuperchargers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='superchargeruse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teslacarinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teslafirmwarehistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teslatoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teslatoken',
            name='vehicle_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='teslatoken',
            constraint=models.UniqueConstraint(fields=('user_id',), name='one_tesla_token_per_user'),
        ),
    ]
