# Generated by Django 5.2.16 on 2026-07-25 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0032_fleet_oauth_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teslatoken',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='teslatoken',
            name='vehicle_id',
        ),
        migrations.RemoveField(
            model_name='teslatoken',
            name='vehicle_vin',
        ),
        migrations.CreateModel(
            name='TeslaVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=64)),
                ('vin', models.CharField(blank=True, default='', max_length=32)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('state', models.CharField(blank=True, default='', max_length=32)),
                ('is_primary', models.BooleanField(default=False, help_text='Default vehicle when none is selected in session')),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tesla_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'display_name', 'vin'],
                'constraints': [models.UniqueConstraint(fields=('user', 'api_id'), name='unique_vehicle_api_id_per_user')],
            },
        ),
    ]
