# Generated by Django 5.2.16 on 2026-07-25 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0033_multi_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeslaOAuthPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tesla_oauth_pendings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tesla OAuth pending state',
                'verbose_name_plural': 'Tesla OAuth pending states',
            },
        ),
    ]
