# Generated by Django 5.2.16 on 2026-07-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0034_oauth_pending_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='teslaappsettings',
            name='partner_domain',
            field=models.CharField(blank=True, default='', help_text='Bare domain e.g. robotcar.example.com — must serve the public key over HTTPS', max_length=255),
        ),
        migrations.AddField(
            model_name='teslaappsettings',
            name='partner_registered',
            field=models.BooleanField(default=False),
        ),
    ]
