# Generated by Django 5.2.16 on 2026-07-26 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0036_remove_supercharger_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='battery_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='battery_heater_on',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='car_version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='charge_current_request',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='charge_current_request_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='charge_energy_added',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='charge_miles_added_ideal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='charge_miles_added_rated',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='charge_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='charge_port_door_open',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='display_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='drive_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='energy_remaining',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='fan_status',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='gps_as_of',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='heading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='ideal_battery_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='idle_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='is_auto_conditioning_on',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='is_front_defroster_on',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='is_rear_defroster_on',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='is_user_present',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='locked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='pack_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='sentry_mode',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='shift_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='sleep_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='time_to_full_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='Date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='DateOnlyDay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='NumberCycles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='battery_degradation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='battery_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='battery_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='charge_limit_soc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='charge_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='charger_actual_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='charger_phases',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='charger_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='charger_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='charging_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='climate_keeper_mode',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='driver_temp_setting',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='est_battery_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='fast_charger_brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='fast_charger_present',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='fast_charger_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='hashedVin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='inside_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='is_climate_on',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='max_range_charge_counter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='odometer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='outside_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='passenger_temp_setting',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='randomNr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teslacardatasnapshot',
            name='usable_battery_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='teslacardatasnapshot',
            index=models.Index(fields=['vin', 'Date'], name='matesla_tes_vin_c9ac40_idx'),
        ),
    ]
