# Generated by Django 5.2.16 on 2026-07-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0037_teslafi_fields_and_floats'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominatimDailyQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('last_call_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
