# Generated by Django 5.2.16 on 2026-07-29 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0040_snapshot_hashedvin_date_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='teslacardatasnapshot',
            new_name='matesla_tes_hashedV_ea7423_idx',
            old_name='matesla_tes_hashedV_date_idx',
        ),
        migrations.RenameIndex(
            model_name='teslacardatasnapshot',
            new_name='matesla_tes_hashedV_9bb581_idx',
            old_name='matesla_tes_hashedV_day_idx',
        ),
    ]
