# Generated by Django 5.2.16 on 2026-08-01 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0042_fleetapicall'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fleetapicall',
            new_name='matesla_fle_hashedV_1aed34_idx',
            old_name='matesla_fle_hashedV_idx',
        ),
        migrations.RenameIndex(
            model_name='fleetapicall',
            new_name='matesla_fle_kind_7a487e_idx',
            old_name='matesla_fle_kind_bi_idx',
        ),
    ]
