# Generated by Django 5.2.16 on 2026-08-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0043_rename_matesla_fle_hashedv_idx_matesla_fle_hashedv_1aed34_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='climate_keeper_modeRaw',
            field=models.TextField(blank=True, null=True),
        ),
    ]
