# Generated by Django 5.2.16 on 2026-08-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0044_teslacardatasnapshot_climate_keeper_moderaw'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teslacardatasnapshot',
            index=models.Index(condition=models.Q(('shift_state__in', ['D', 'R', 'N']), ('speed__gt', 1), _connector='OR'), fields=['hashedVin', 'Date'], name='matesla_snapshot_drive_hv_date'),
        ),
    ]
