# Generated by Django 5.2.16 on 2026-08-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0045_snapshot_partial_drive_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='active_route_destination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='active_route_miles_to_arrival',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teslacardatasnapshot',
            name='active_route_minutes_to_arrival',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
