# Generated by Django 5.2.16 on 2026-08-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0048_snapshot_lat_lon_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teslacardatasnapshot',
            index=models.Index(condition=models.Q(('charging_state__in', ['Charging', 'Starting']), ('charge_number__isnull', False)), fields=['hashedVin', 'charge_number'], name='matesla_snap_charge_sess_idx'),
        ),
    ]
