# Generated by Django 5.2.16 on 2026-09-12 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0049_snapshot_charge_session_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeCostSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_eur_per_kwh', models.FloatField(blank=True, help_text='€/kWh for chargers that are not home, work, or a Supercharger', null=True)),
                ('supercharger_eur_per_kwh', models.FloatField(blank=True, help_text='€/kWh when no Tesla Supercharger invoice is available', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charge_cost_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChargePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_m', models.PositiveIntegerField(default=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_places', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeSessionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_vin', models.CharField(db_index=True, max_length=64)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('kwh', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rule', models.CharField(choices=[('home_flat', 'Home (flat)'), ('home_day_night', 'Home (day / night)'), ('home_dynamic', 'Home (dynamic)'), ('work', 'Work'), ('supercharger_invoice', 'Tesla Supercharger invoice'), ('supercharger_rate', 'Supercharger average rate'), ('other', 'Other chargers'), ('unpriced', 'Unpriced')], default='unpriced', max_length=32)),
                ('status', models.CharField(choices=[('priced', 'Priced'), ('unpriced', 'Unpriced'), ('partial', 'Partial')], default='unpriced', max_length=16)),
                ('cost_eur', models.FloatField(blank=True, null=True)),
                ('tesla_invoice_eur', models.FloatField(blank=True, null=True)),
                ('tesla_session_id', models.CharField(blank=True, default='', max_length=64)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_costs', to='matesla.chargeplace')),
            ],
        ),
        migrations.CreateModel(
            name='DayAheadSpotPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtu_start', models.DateTimeField(db_index=True)),
                ('resolution_minutes', models.PositiveSmallIntegerField()),
                ('price_eur_mwh', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['mtu_start'], name='matesla_day_mtu_sta_c4a7a6_idx')],
                'constraints': [models.UniqueConstraint(fields=('mtu_start', 'resolution_minutes'), name='dayahead_spot_unique_mtu')],
            },
        ),
        migrations.CreateModel(
            name='PlaceTariffPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('flat', 'Flat'), ('day_night', 'Day / night'), ('dynamic', 'Dynamic (day-ahead + cents)')], default='flat', max_length=16)),
                ('flat_eur_per_kwh', models.FloatField(blank=True, null=True)),
                ('day_eur_per_kwh', models.FloatField(blank=True, null=True)),
                ('night_eur_per_kwh', models.FloatField(blank=True, null=True)),
                ('night_start', models.TimeField(default='22:00:00')),
                ('night_end', models.TimeField(default='07:00:00')),
                ('dynamic_surcharge_cents', models.IntegerField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_periods', to='matesla.chargeplace')),
            ],
            options={
                'ordering': ['valid_from'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePlaceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_vin', models.CharField(db_index=True, max_length=64)),
                ('role', models.CharField(choices=[('home', 'Home'), ('work', 'Work')], max_length=16)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_roles', to='matesla.chargeplace')),
            ],
        ),
        migrations.AddIndex(
            model_name='chargeplace',
            index=models.Index(fields=['user'], name='matesla_cha_user_id_566628_idx'),
        ),
        migrations.AddIndex(
            model_name='chargesessioncost',
            index=models.Index(fields=['hashed_vin', 'start'], name='matesla_cha_hashed__21cbb3_idx'),
        ),
        migrations.AddIndex(
            model_name='chargesessioncost',
            index=models.Index(fields=['hashed_vin', 'end'], name='matesla_cha_hashed__1a4ca3_idx'),
        ),
        migrations.AddConstraint(
            model_name='chargesessioncost',
            constraint=models.UniqueConstraint(fields=('hashed_vin', 'start'), name='charge_session_cost_unique_start'),
        ),
        migrations.AddIndex(
            model_name='placetariffperiod',
            index=models.Index(fields=['place', 'valid_from'], name='matesla_pla_place_i_b8f45d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleplacerole',
            index=models.Index(fields=['hashed_vin', 'role', 'valid_from'], name='matesla_veh_hashed__cd05cd_idx'),
        ),
    ]
