# Generated by Django 5.2.16 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matesla", "0050_charge_cost_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeslaChargingHistorySync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hashed_vin", models.CharField(max_length=64, unique=True)),
                ("last_ok_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, default="", max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name="TeslaChargingInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hashed_vin", models.CharField(db_index=True, max_length=64)),
                ("tesla_session_id", models.CharField(max_length=64, unique=True)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("site_name", models.CharField(blank=True, default="", max_length=256)),
                ("total_eur", models.FloatField()),
                ("kwh", models.FloatField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, default="EUR", max_length=8)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="teslacharginginvoice",
            index=models.Index(
                fields=["hashed_vin", "start"],
                name="matesla_tes_hashed__c9e1a2_idx",
            ),
        ),
    ]
