# Generated by Django 5.2.16 on 2026-09-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matesla', '0053_place_tariff_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardGeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_key', models.CharField(max_length=240, unique=True)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='forwardgeocodecache',
            index=models.Index(fields=['fetched_at'], name='matesla_for_fetched_38a76d_idx'),
        ),
    ]
