# Generated by Django 5.2.16 on 2026-07-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carimage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teslaimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
